# -*- coding: utf-8 -*-

"""
youtubeapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CustomQueryAuthentication:

    def __init__(self, key):
        self._key = key

    def validate_arguments(self):
        if self._key:
            return True
        return False

    def apply(self, http_request):
        """ Add custom authentication to the request.

        Args:
            http_request (HttpRequest): The HttpRequest object to which
                authentication will be added.

        """
        http_request.add_query_parameter("key", self._key)

    def error_message(self):
        """Display error message on occurrence of authentication faliure
        in CustomQueryAuthentication

        """
        return "CustomQueryAuthentication: _key is undefined."
